### ISSUE TITLE
[bug] tags match outside comments in markdown files

### ISSUE THREAD

**Issue by Fred-Vatin** [Zxynine/EvenBetterComments#4]
![image](https://user-images.githubusercontent.com/22337329/204128252-c19494c2-4cf2-4ddf-9ed8-c363348f00da.png)

**Comment by Zxynine** [comment]
That’s very odd, can you do me a favour, I am out of the house today, hop into the file, press control shift p to open up the command pallets and find the “show line tokens” command from even better comments. Have the line with the unexpected highlights selected and it should output all of the tokens for that line into the console. I have a feeling that markdown files don’t have a proper single line comment delimeter so everything appears as a comment or something

**Comment by Fred-Vatin** [comment]
Here it is when it’s a markdown comment
![image](https://user-images.githubusercontent.com/22337329/204163822-c747bb5f-f417-4fb3-8010-fd44de0d4974.png)

```yml
Text: '<!--'
Line: 5
Length: 4
Scopes:
  - comment.block.html
  - punctuation.definition.comment.html
  - text.html.markdown
Base Scope: comment

---
Text: ' todo '
Line: 5
Length: 6
Scopes:
  - comment.block.html
  - text.html.markdown
Base Scope: comment

---
Text: '-->'
Line: 5
Length: 3
Scopes:
  - comment.block.html
  - punctuation.definition.comment.html
  - text.html.markdown
Base Scope: comment
```

---

Here it is when it matches outside of comment in markdown
![image](https://user-images.githubusercontent.com/22337329/204163869-a023f66f-7f79-4968-afe5-1a2b51d15db7.png)

```yml
Text: 'todo'
Line: 7
Length: 4
Scopes:
  - meta.paragraph.markdown
  - text.html.markdown
Base Scope: meta
```
